# PostgreSQL. Versions 8.2 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: splurty_development

test:
  <<: *default
  database: splurty_test

production:
  <<: *default
  database: splurty_production